import { StyleSheet } from 'react-native';

export const styles = StyleSheet.create({
  container: { flex: 1, backgroundColor: '#F8F9FA' },
  center: { justifyContent: 'center', alignItems: 'center' },
  header: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingHorizontal: 16,
    height: 56,
    backgroundColor: '#FFF',
    borderBottomWidth: 1,
    borderBottomColor: '#EEE',
  },
  backButton: { width: 40, height: 40, justifyContent: 'center' },
  headerTitle: { fontSize: 18, fontWeight: 'bold', color: '#333' },
  searchContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#FFF',
    marginHorizontal: 16,
    marginTop: 12,
    marginBottom: 4,
    borderRadius: 8,
    paddingHorizontal: 12,
    borderWidth: 1,
    borderColor: '#DDD',
  },
  searchIcon: { marginRight: 8 },
  searchInput: { flex: 1, height: 40, fontSize: 15, color: '#333' },
  listContainer: { padding: 16 },
  userCard: {
    backgroundColor: '#FFF',
    borderRadius: 12,
    padding: 16,
    marginBottom: 12,
    elevation: 2,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.1,
    shadowRadius: 2,
  },
  userInfo: { marginBottom: 12 },
  nameRow: { flexDirection: 'row', alignItems: 'center', marginBottom: 4 },
  userName: { fontSize: 17, fontWeight: 'bold', color: '#333', marginRight: 8 },
  userDetail: { fontSize: 14, color: '#666', marginBottom: 4 },
  dateText: { fontSize: 12, color: '#999' },
  roleBadge: { paddingHorizontal: 8, paddingVertical: 2, borderRadius: 4 },
  superBadge: { backgroundColor: '#F3E8FF' },
  adminBadge: { backgroundColor: '#FFF0F2' },
  userBadge: { backgroundColor: '#F0F1F4' },
  roleText: { fontSize: 11, fontWeight: '600', color: '#FF4D6D' },
  actionButtons: { flexDirection: 'row', gap: 8, borderTopWidth: 1, borderTopColor: '#F5F5F5', paddingTop: 12 },
  actionButton: {
    flex: 1,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    paddingVertical: 8,
    borderRadius: 8,
    borderWidth: 1,
    gap: 4,
  },
  roleButton: { borderColor: '#DDD', backgroundColor: '#FFF' },
  deleteButton: { borderColor: '#FFC0CB', backgroundColor: '#FFF' },
  actionButtonText: { fontSize: 13, fontWeight: '600', color: '#555' },
});
