import { StyleSheet, Platform } from 'react-native';

export const styles = StyleSheet.create({
  container: { flex: 1, backgroundColor: '#F8F9FA' },
  header: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingHorizontal: 16,
    height: 56,
    backgroundColor: '#FFF',
    borderBottomWidth: 1,
    borderBottomColor: '#EEE',
    zIndex: 10,
  },
  backButton: { width: 40, height: 40, justifyContent: 'center' },
  headerTitle: { flex: 1, textAlign: 'center', fontSize: 18, fontWeight: 'bold', color: '#333' },
  menuButton: { width: 40, height: 40, justifyContent: 'center', alignItems: 'flex-end' },
  menuOverlay: {
    position: 'absolute',
    top: 56, // 헤더 높이만큼 아래에 위치 (Safe area 밖이므로 약간 조정이 필요할수도)
    left: 0,
    right: 0,
    bottom: 0,
    zIndex: 20,
  },
  menuBox: {
    position: 'absolute',
    top: Platform.OS === 'ios' ? 60 : 10,
    right: 16,
    backgroundColor: '#FFF',
    borderRadius: 8,
    elevation: 5,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 4,
    width: 150,
    zIndex: 30,
  },
  menuItem: { paddingVertical: 14, paddingHorizontal: 16 },
  menuDivider: { height: 1, backgroundColor: '#EEE' },
  menuItemText: { fontSize: 15, color: '#333', textAlign: 'center' },
  
  modalBackground: {
    flex: 1,
    backgroundColor: 'rgba(0,0,0,0.5)',
    justifyContent: 'flex-end',
  },
  modalContainer: {
    backgroundColor: '#FFF',
    borderTopLeftRadius: 20,
    borderTopRightRadius: 20,
    padding: 20,
    maxHeight: '80%',
  },
  modalHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 10,
  },
  modalTitle: { fontSize: 18, fontWeight: 'bold', color: '#333' },
  modalSubtitle: { fontSize: 14, color: '#666', marginBottom: 20 },
  reportMessageItem: {
    flexDirection: 'row',
    alignItems: 'center',
    padding: 15,
    borderRadius: 12,
    backgroundColor: '#F5F6F8',
    marginBottom: 10,
  },
  reportMessageItemSelected: {
    backgroundColor: '#FFF0F2',
    borderColor: '#FF4D6D',
    borderWidth: 1,
  },
  reportMessageText: { fontSize: 15, color: '#333', marginLeft: 10, flex: 1 },
  submitReportButton: {
    backgroundColor: '#FF4D6D',
    padding: 16,
    borderRadius: 12,
    alignItems: 'center',
    marginTop: 10,
  },
  submitReportText: { color: '#FFF', fontSize: 16, fontWeight: 'bold' },

  messageList: { padding: 16, paddingBottom: 20 },
  messageContainer: { marginBottom: 16, maxWidth: '80%' },
  myMessageContainer: { alignSelf: 'flex-end', alignItems: 'flex-end' },
  otherMessageContainer: { alignSelf: 'flex-start', alignItems: 'flex-start' },
  bubble: { paddingHorizontal: 16, paddingVertical: 10, borderRadius: 20 },
  myBubble: { backgroundColor: '#FF4D6D', borderBottomRightRadius: 4 },
  otherBubble: { backgroundColor: '#FFF', borderBottomLeftRadius: 4, borderWidth: 1, borderColor: '#EEE' },
  messageText: { fontSize: 15, lineHeight: 20 },
  myMessageText: { color: '#FFF' },
  otherMessageText: { color: '#333' },
  timeText: { fontSize: 10, color: '#999', marginTop: 4, marginHorizontal: 4 },
  inputContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    padding: 10,
    backgroundColor: '#FFF',
    borderTopWidth: 1,
    borderTopColor: '#EEE',
  },
  plusButton: { padding: 8 },
  input: {
    flex: 1,
    backgroundColor: '#F0F1F4',
    borderRadius: 20,
    paddingHorizontal: 16,
    paddingVertical: 8,
    marginHorizontal: 8,
    fontSize: 15,
    maxHeight: 100,
  },
  sendButton: {
    width: 40,
    height: 40,
    borderRadius: 20,
    backgroundColor: '#FF4D6D',
    justifyContent: 'center',
    alignItems: 'center',
  },
  sendButtonDisabled: { backgroundColor: '#FFC0CB' },
});
