import { StyleSheet } from 'react-native';

export const styles = StyleSheet.create({
  container: { flex: 1, backgroundColor: '#F8F9FA' },
  header: { 
    flexDirection: 'row',
    paddingHorizontal: 20, 
    height: 60,
    borderBottomWidth: 1, 
    borderBottomColor: '#F0F0F0', 
    backgroundColor: '#FFF', 
    alignItems: 'center',
    justifyContent: 'space-between'
  },
  headerTitle: { fontSize: 20, fontWeight: 'bold', color: '#333' },
  logoutButton: { padding: 8 },
  logoutText: { color: '#FF4D6D', fontWeight: 'bold', fontSize: 14 },
  content: { flex: 1, padding: 20 },
  adminInfoCard: {
    backgroundColor: '#FFF',
    padding: 24,
    borderRadius: 16,
    alignItems: 'center',
    marginBottom: 24,
    elevation: 2,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 4,
  },
  adminId: { fontSize: 18, fontWeight: 'bold', marginTop: 12, marginBottom: 4 },
  adminDesc: { fontSize: 14, color: '#666' },
  sectionTitle: { fontSize: 16, fontWeight: 'bold', color: '#333', marginBottom: 12, marginLeft: 4 },
  statsContainer: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 12,
  },
  statCard: {
    flex: 1,
    minWidth: '45%',
    backgroundColor: '#FFF',
    padding: 16,
    borderRadius: 12,
    alignItems: 'center',
    elevation: 2,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.05,
    shadowRadius: 2,
  },
  statLabel: { fontSize: 13, color: '#888', marginBottom: 6 },
  statValue: { fontSize: 24, fontWeight: 'bold', color: '#333' },
  menuContainer: { backgroundColor: '#FFF', borderRadius: 16, overflow: 'hidden' },
  menuItem: {
    flexDirection: 'row',
    alignItems: 'center',
    padding: 16,
    borderBottomWidth: 1,
    borderBottomColor: '#F0F0F0',
  },
  menuText: { fontSize: 16, marginLeft: 16, color: '#333' },
});
